version: '2'
services:
    kaylenewifi-app:
        image: kaylenewifi
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://kaylenewifi-mysql:3306/kaylenewifi?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kaylenewifi-mysql:
        extends:
            file: mysql.yml
            service: kaylenewifi-mysql
